name = "filesnaps-worker"
main = "src/index.js"
compatibility_date = "2025-05-24"

[triggers]
crons = ["0 */2 * * *"]

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "filesnaps-uploads"

[[kv_namespaces]]
binding = "FILE_META"
id = "YOUR_KV_NAMESPACE_ID"
